# Generated by Django 2.2.6 on 2019-10-22 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Nombre')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('payment_type', models.CharField(choices=[('CA', 'Efectivo'), ('CC', 'Credito'), ('DB', 'Debito')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Nombre')),
                ('description', models.TextField(max_length=500, verbose_name='Descripcion')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Precio')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='menu.Category')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products')),
                ('suitForVegetarian', models.BooleanField(default=False, verbose_name='Apto para Vegetarianos')),
                ('suitForGlutenIntolerant', models.BooleanField(default=False, verbose_name='Apto para Celíacos')),
            ],
        ),
        migrations.CreateModel(
            name='DailySpecial',
            fields=[
                ('type', models.CharField(
                    choices=[('FP', 'Entrada'), ('MP', 'Plato principal'), ('DE', 'Postre'), ('DK', 'Bebida')],
                    max_length=2, primary_key=True, serialize=False, verbose_name='Tipo')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product',
                                              to='menu.Product', verbose_name='Producto')),
            ],
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('name', models.CharField(max_length=30, verbose_name='Nombre')),
                ('email', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Mail')),
                ('token', models.CharField(blank=True, default=None, max_length=20, verbose_name='token')),
            ],
        ),
    ]
