# Generated by Django 2.2.6 on 2019-10-25 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='suitForGlutenIntolerant',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='suitForVegetarian',
            field=models.BooleanField(default=False),
        ),
    ]
