# Generated by Django 2.2.6 on 2019-10-27 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_auto_20191025_1702'),
    ]

    operations = [
        migrations.CreateModel(
            name='TodaysMenuDish',
            fields=[
                ('type', models.CharField(choices=[('FP', 'Entrada'), ('MP', 'Plato principal'), ('DE', 'Postre'), ('DK', 'Bebida')], max_length=2, primary_key=True, serialize=False, verbose_name='Tipo')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='menu.Product', verbose_name='Producto')),
            ],
        ),
    ]
