# Generated by Django 2.2.6 on 2019-10-22 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_product_category'),
        ('menu', '0004_auto_20191020_2323'),
    ]

    operations = [
    ]
