# Generated by Django 2.2.6 on 2019-10-22 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_merge_20191022_0222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethod',
            name='payment_type',
            field=models.CharField(choices=[('CA', 'Efectivo'), ('CC', 'Credito'), ('DB', 'Debito')], max_length=2),
        ),
    ]
