# Generated by Django 2.2.6 on 2019-10-30 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0007_client'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(null=True, upload_to='Desktop'),
        ),
    ]
