# Generated by Django 2.2.6 on 2019-11-03 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0008_auto_20191031_1917'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products'),
        ),
        migrations.AlterField(
            model_name='product',
            name='suitForGlutenIntolerant',
            field=models.BooleanField(default=False, verbose_name='Apto para Celíacos'),
        ),
        migrations.AlterField(
            model_name='product',
            name='suitForVegetarian',
            field=models.BooleanField(default=False, verbose_name='Apto para Vegetarianos'),
        ),
    ]
