# Generated by Django 2.2.6 on 2019-10-30 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0008_auto_20191030_0202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(null=True, upload_to='Menu/templates/product/images'),
        ),
    ]
