# Generated by Django 2.2.6 on 2019-10-31 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0009_auto_20191030_0217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='suitForGlutenIntolerant',
            field=models.BooleanField(default=False, verbose_name='Apto para Celíacos'),
        ),
        migrations.AlterField(
            model_name='product',
            name='suitForVegetarian',
            field=models.BooleanField(default=False, verbose_name='Apto para Vegetarianos'),
        ),
    ]
